# Generated by Django 3.2.7 on 2021-09-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skins', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skin',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
